import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import NavBar from "@/components/nav-bar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
      >
        <div className="max-w-[1200px] mx-auto flex gap-10 ">
          <div className="w-full sticky top-0 p-4">
            <NavBar />
          </div>
          <div className="w-full my-20 overflow-y-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}
